### ISSUE TITLE
Not work in heroku

### ISSUE THREAD

**Issue by darky** [imagemin/jpegtran-bin#42]
Error: /app/node_modules/grunt-contrib-imagemin/node_modules/jpegtran-bin/vendor/jpegtran: 1: Syntax error: "(" unexpected
✔ app/images/warranty.jpg (already optimized)

**Comment by katherine-barn2door** [comment]
I'm seeing this issue. I feel like gulp or one of the gulp components didn't install correctly when I created this vagrant. But any thoughts would be appreciated.

```vagrant@packer-virtualbox-iso-1422601639:~/website$ gulp build
[17:10:34] Using gulpfile ~/website/gulpfile.js
[17:10:34] Starting 'images'...
[17:10:34] Finished 'images' after 133 ms
[17:10:34] Starting 'browserify-site'...
[17:10:34] Starting 'vendor-scripts'...
[17:10:34] Starting 'vendor-copy'...
[17:10:34] Starting 'image-upload-scripts'...
[17:10:34] Starting 'datepicker-scripts'...
[17:10:34] Starting 'site-styles'...
[17:10:34] Starting 'copy-styles'...
[17:10:34] Starting 'fonts'...

events.js:141
      throw er; // Unhandled 'error' event
      ^
Error: /home/vagrant/website/node_modules/gulp-imagemin/node_modules/imagemin/node_modules/imagemin-jpegtran/node_modules/jpegtran-bin/vendor/jpegtran: 1: /home/vagrant/website/node_modules/gulp-imagemin/node_modules/imagemin/node_modules/imagemin-jpegtran/node_modules/jpegtran-bin/vendor/jpegtran: Syntax error: "(" unexpected

    at ChildProcess.<anonymous> (/home/vagrant/website/node_modules/gulp-imagemin/node_modules/imagemin/node_modules/imagemin-jpegtran/index.js:62:37)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:821:16)
    at Socket.<anonymous> (internal/child_process.js:319:11)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at Pipe._onclose (net.js:469:12)
vagrant@packer-virtualbox-iso-1422601639:~/website$ npm list | grep imagemin
├─┬ gulp-imagemin@2.4.0
│ ├─┬ imagemin@4.0.0
│ │ ├─┬ imagemin-gifsicle@4.2.0
│ │ ├─┬ imagemin-jpegtran@4.3.2
│ │ ├─┬ imagemin-optipng@4.3.0
│ │ ├─┬ imagemin-svgo@4.2.0
vagrant@packer-virtualbox-iso-1422601639:~/website$ npm list | grep jpegtran
│ │ ├─┬ imagemin-jpegtran@4.3.2
│ │ │ ├─┬ jpegtran-bin@3.0.6
vagrant@packer-virtualbox-iso-1422601639:~/website$ 
```

**Comment by rvanlaarhoven** [comment]
Although I had the same issue while using `gulp-imagemin@2.4.0`, running `npm update gulp-imagemin` solved it.

**Comment by katherine-barn2door** [comment]
I believe in the end 'npm rebuild' or uninstall/install fixed it. The trouble is my node_modules folders are shared between OSX and a Linux vagrant, so gulp isn't compatible going back and forth, because of the C libraries.

**Comment by CaptainStaplerz** [comment]
I have the very exact same issue with docker. What do I do to solve it?
I use imagemin@2.4.0 (latest after a npm update).
It's like @katherine-barn2door said. It seems that when I'm mounting a folder from my OSX to docker (this is for development) the error occurs.

**Comment by katherine-barn2door** [comment]
@CaptainStaplerz did you try npm update, or else npm uninstall and install for the offending module?

**Comment by CaptainStaplerz** [comment]
Do you mean inside my socket container?
The thing is that I want gulp to be running tasks while I develop on the app locally on my computer.
I don't think I quite follow :)

**Comment by katherine-barn2door** [comment]
@CaptainStaplerz I've got no familiarity with docker, so perhaps that solution doesn't apply.

I'll give you some more context if it helps. Whatever your environment is, be it a VM or a local machine, these native libraries have to be compiled to that OS. I was having lots of problems because I was doing npm installs locally on my OSX, but then RUNNING my server in a vagrant VM which was linux. That doesn't fly with C libraries.

**Comment by CaptainStaplerz** [comment]
Uhm, I tought I wrote an answer (guess not). But it seems to me that i have the same problem. Now I have to figure out a workaround for my case. Thanks for sharing btw.

**Comment by boboldehampsink** [comment]
@katherine-barn2door thanks for the answer. In my case, Docker added node_modules from OSX to the image. I had to delete node_modules on OSX and have them installed INSIDE the container only, so that the binaries were linux compatible.

**Comment by katherine-barn2door** [comment]
Huh. @boboldehampsink that should be be what "npm uninstall" and "npm install" would be be doing, delete and recreating the node_modules folders. Glad you're working.
