### ISSUE TITLE
Can't install on Win 7 64 bits (can't download jpegtran.exe)

### ISSUE THREAD

**Issue by pjfsilva** [imagemin/jpegtran-bin#54]
I'm trying to install jpegtran-bin by doing:
npm cache clean -f
npm install jpegtran-bin

The error I get is:

```
npm info postinstall jpegtran-bin@2.0.2

> jpegtran-bin@2.0.2 postinstall C:\a\node_modules\jpegtran-bin
> node lib/install.js

  ‼ ENOENT, stat 'C:\a\node_modules\jpegtran-bin\vendor\jpegtran.exe'
  ‼ jpegtran pre-build test failed
  i compiling from source
  × Error: Command failed: '.' is not recognized as an internal or external comm
and,
operable program or batch file.

    at ChildProcess.exithandler (child_process.js:648:15)
    at ChildProcess.emit (events.js:98:17)
    at maybeClose (child_process.js:756:16)
    at Process.ChildProcess._handle.onexit (child_process.js:823:5)
```

Checking my vendor folder it seems the file win/x64/jpegtran.exe isn't downloaded, I only have "libjpeg-62.dll" but I can't see any error even using -ddd switch. I've disabled antivirus and stuff like that and I tried over 2 networks with no luck...

Is there anything I can do to get more log or understand this better?

**Comment by liuningnggirl** [comment]
@tedyoung感谢您的解决方案
