### ISSUE TITLE
"binary doesn't seem to work properly"

### ISSUE THREAD

**Issue by uorbe001** [imagemin/jpegtran-bin#60]
We are having really slow build times (from a clean workspace) because imagemin is trying to install all these dependencies and they are all giving us a "binary doesn't seem to work properly" error, so it tries to compile all of them (which adds about 4-5 minutes to our build time). We are using linux 64bit, and there seems to be a pre-built binary for that which we were hoping to be able to get to work, but we've had no luck so far. This is our system:
```
$uname -ar 
Linux myhost 3.2.0-4-amd64 #1 SMP Debian 3.2.68-1+deb7u1 x86_64 GNU/Linux
```
Is there any way to get all these jpegtran-bin, gifsicle-bin etc libraries to use the binary installed in our $PATH or feed them a prebuilt binary that we know works? 

I've tried looking at the source code and from what I understand, they are all using bin-wrapper and using the binaries on /vendor, so I figured it might be possible to try to load one from the $PATH adding a line here https://github.com/imagemin/jpegtran-bin/blob/master/lib/index.js#L18. Not sure if there's a valid reason against it, so I'd rather ask before trying to modify all the libraries.

**Comment by kevva** [comment]
@uorbe001, could you try reinstalling and see if https://github.com/imagemin/jpegtran-bin/pull/63 fixed this?

**Comment by uorbe001** [comment]
@kevva yes, it seems to be using the binary now, thanks!
