### ISSUE TITLE
linux binary 1.3.1 doesn't work on CentOS 6

### ISSUE THREAD

**Issue by andkononykhin** [imagemin/jpegtran-bin#61]
Current linux x64 binary (1.3.1) requires GLIBC 2.14.
Could you rebuild it to make compatible with CentOS 6 (uses glibc 2.12) as it was for previous version?
Thanks

**Comment by kevva** [comment]
@andkononykhin, can you try installing again and see if https://github.com/imagemin/jpegtran-bin/pull/63 fixed this?

**Comment by andkononykhin** [comment]
@kevva, yes, it works now. Thank you.

**Comment by kevva** [comment]
Good times!
