### ISSUE TITLE
The download in lib/install.js do not use npm corporate proxy

### ISSUE THREAD

**Issue by jmorille** [imagemin/jpegtran-bin#66]
The donwload mecanism used in the install script lib/install.js do direct download to ( https://raw.githubusercontent.com/imagemin/*)  that do not use  corporate npm proxy installed in my company (in this case Sonatype Nexus).

This direct download break somes developpement constraint, that need to be respected in bank or assurance company, like  DRP ( Disaster Recovery Plan) or BCP, (Business Continuity Planning).

This change of direct download to npm download mechanism permit in more to accelerate the download for all developper by local caching in the npm corporate registry.

**Comment by kevva** [comment]
https://github.com/kevva/download/issues/64
