### ISSUE TITLE
Installing behind proxy fails

### ISSUE THREAD

**Issue by ac-astuartkregor** [imagemin/jpegtran-bin#67]
Hello,

It seems like version 3.0.5 is failing to fetch the jpegtran binary when behind a proxy, although it was working recently. Forcing the version to be 3.0.4 fixes the issue, therefore the problem exists in 3.0.5.
The proxy is being set through environment variables.

**Comment by shinnn** [comment]
Discussions related to this problem goes to https://github.com/kevva/download/issues/64.

**Comment by ac-astuartkregor** [comment]
Could you please explain how this is a problem with the download package, since the only thing that has changed in the last two days is the version of jpegtran-bin? On Friday, npm successfully installed jpegtran-bin version 3.0.4 and today version 3.0.5 is failing to install. I cannot see any changes in the version of download.

**Comment by shinnn** [comment]
Ah, OK. I guess [changing download URL protocol from HTTP to HTTPS](https://github.com/imagemin/jpegtran-bin/commit/81da2678d86dd2d62292a3eed8f5ff1cfc2ccd7f) caused the error.

But I still think this is a `download` issue. It should handle both HTTP and HTTPS correctly.

Anyway I'll restore the protocol to HTTPS again.

**Comment by BookOfGreg** [comment]
Thanks @shinnn, was just about to comment with this same exact issue.

**Comment by ac-astuartkregor** [comment]
Thanks very much for clarifying @shinnn. I agree the `download` module should handle it properly, and we do set both the http and https proxy variables.

**Comment by marc-guenther** [comment]
mikeal/tunnel-agent#15 fixed this problem for us.

**Comment by ac-astuartkregor** [comment]
Fingers crossed that it gets published quickly.

**Comment by marc-guenther** [comment]
workaround in the mean time is to specify port 443 in the url explicitely ;)

**Comment by marc-guenther** [comment]
New version of [tunnel-agent@0.4.2](https://www.npmjs.com/package/tunnel-agent) has just been released. This contains the mikeal/tunnel-agent#15 fix. :-)

**Comment by shinnn** [comment]
OK, I won't restore the protocol to HTTPS.
