### ISSUE TITLE
Failed at the jpegtran-bin@0.2.0 postinstall script 'node pre-build.js'.

### ISSUE THREAD

**Issue by lukepuplett** [imagemin/jpegtran-bin#71]
Failure to install on Windows 7 running under Command Prompt as Administrator.

Disclaimer: I'm new to npm, grunt etc. and have been having problems with npm on Windows for a week now, my understanding is that this stuff is meant to just work, though I have a suspicion that Windows is less used and more likely where the bugs are. I'm not really sure how to troubleshoot, sorry.

The end of the more -in-depth npm log is at the bottom.

npm WARN mgmQuote@0.0.0 No repository field.
npm WARN mgmQuote@0.0.0 No license field.
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v5.1.1
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE

npm ERR! jpegtran-bin@0.2.0 postinstall: `node pre-build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the jpegtran-bin@0.2.0 postinstall script 'node pre-build.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the jpegtran-bin package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node pre-build.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs jpegtran-bin
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls jpegtran-bin
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\DATA\Git\The Censored Product\Web.UI\npm-debug.log

-- npm-debug.log follows --

...
90431 info lifecycle jpegtran-bin@0.2.0~postinstall: jpegtran-bin@0.2.0
90432 verbose lifecycle jpegtran-bin@0.2.0~postinstall: unsafe-perm in lifecycle true
90433 verbose lifecycle jpegtran-bin@0.2.0~postinstall: PATH: C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;C:\DATA\Git\The Censored Product\Web.UI\node_modules\jpegtran-bin\node_modules\.bin;C:\DATA\Git\The Censored Product\Web.UI\node_modules\.bin;[Censored Values];C:\Program Files\nodejs\;C:\Program Files\Git\cmd;C:\Users\user.name\AppData\Roaming\npm
90434 verbose lifecycle jpegtran-bin@0.2.0~postinstall: CWD: C:\DATA\Git\The Censored Product\Web.UI\node_modules\jpegtran-bin
90435 silly lifecycle jpegtran-bin@0.2.0~postinstall: Args: [ '/d /s /c', 'node pre-build.js' ]
90436 silly lifecycle jpegtran-bin@0.2.0~postinstall: Returned: code: 1  signal: null
90437 info lifecycle jpegtran-bin@0.2.0~postinstall: Failed to exec postinstall script
90438 verbose unlock done using C:\Users\user.name\AppData\Roaming\npm-cache\_locks\staging-686cce0fed838b08.lock for C:\DATA\Git\The Censored Product\Web.UI\node_modules\.staging
90439 silly rollbackFailedOptional Starting
90440 silly rollbackFailedOptional Finishing
90441 silly runTopLevelLifecycles Starting
90442 silly runTopLevelLifecycles Finishing
90443 silly install printInstalled
90444 warn mgmQuote@0.0.0 No repository field.
90445 warn mgmQuote@0.0.0 No license field.
90446 verbose stack Error: jpegtran-bin@0.2.0 postinstall: `node pre-build.js`
90446 verbose stack Exit status 1
90446 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:232:16)
90446 verbose stack     at emitTwo (events.js:87:13)
90446 verbose stack     at EventEmitter.emit (events.js:172:7)
90446 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:24:14)
90446 verbose stack     at emitTwo (events.js:87:13)
90446 verbose stack     at ChildProcess.emit (events.js:172:7)
90446 verbose stack     at maybeClose (internal/child_process.js:818:16)
90446 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
90447 verbose pkgid jpegtran-bin@0.2.0
90448 verbose cwd C:\DATA\Git\The Censored Product\Web.UI
90449 error Windows_NT 6.1.7601
90450 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
90451 error node v5.1.1
90452 error npm  v3.5.2
90453 error code ELIFECYCLE
90454 error jpegtran-bin@0.2.0 postinstall: `node pre-build.js`
90454 error Exit status 1
90455 error Failed at the jpegtran-bin@0.2.0 postinstall script 'node pre-build.js'.
90455 error Make sure you have the latest version of node.js and npm installed.
90455 error If you do, this is most likely a problem with the jpegtran-bin package,
90455 error not with npm itself.
90455 error Tell the author that this fails on your system:
90455 error     node pre-build.js
90455 error You can get information on how to open an issue for this project with:
90455 error     npm bugs jpegtran-bin
90455 error Or if that isn't available, you can get their info via:
90455 error     npm owner ls jpegtran-bin
90455 error There is likely additional logging output above.
90456 verbose exit [ 1, true ]

**Comment by shinnn** [comment]
> @0.2.0

Please do not use such an ancient version. The latest version is v3.0.6.
