### ISSUE TITLE
Update windows binary

### ISSUE THREAD

**Issue by Delagen** [imagemin/jpegtran-bin#73]
imagemin/imagemin-jpegtran#18

(EDIT: @shinnn)

> feature not selected when compiling
> 
> I think included exe need to rebuild with included feature
> 
> http://jpegclub.org/jpegtran/ contains another exe

**Comment by shinnn** [comment]
Fixed in https://github.com/imagemin/jpegtran-bin/commit/c913b99069d28ea2ba5002ed2bea042eaa0cc272.
