### ISSUE TITLE
Undocumented dependency on Netwide Assembler on Ubuntu, NodeJS v0.8.14

### ISSUE THREAD

**Issue by bogdanbiv** [imagemin/jpegtran-bin#9]
Installing  jpegtran-bin results with the following message:
    $ npm install jpegtran-bin

```
> jpegtran-bin@0.1.3 postinstall /home/bogdanbiv/tmp/nasm-test/node_modules/jpegtran-bin
> node build.js

{ [Error: Command failed: configure: error: no nasm (Netwide Assembler) found
] killed: false, code: 1, signal: null }
```

OS: Ubuntu 12.10 64bit, kernel 3.5.0-26-generic;
NPM 1.1.65, NodeJS: v0.8.14
Other OS & node configurations are untested

**Comment by Hikariii** [comment]
I just installed jpegtran-bin on ubuntu 16 and node v6.4.0 with npm 5.0.3, during compilation.

```jpegtran-bin@3.2.0 postinstall ../node_modules/jpegtran-bin```

Got the following error:
```
Error: touch configure.ac aclocal.m4 configure Makefile.am Makefile.in && ./configure --disable-shared --prefix="../node_modules/jpegtran-bin/vendor" --bindir="../node_modules/jpegtran-bin/vendor" && make install
Command failed: ./configure --disable-shared --prefix="../node_modules/jpegtran-bin/vendor" --bindir="../node_modules/jpegtran-bin/vendor"
configure: error: no nasm (Netwide Assembler) found
```

But, I did not see this represented in the current README.
Why is the dependency removed from the readme?

**Comment by Hikariii** [comment]
Should this be reopened?

**Comment by RacerBas** [comment]
Try `sudo apt-get nasm` first

**Comment by Hikariii** [comment]
True, my issue is NOT with nasm being needed.
My issue is that this dependency is NOT in the readme anymore.

**Comment by EmilMoe** [comment]
Seems to be an issue on Debian 9 too.

`sudo apt-get install nasm` solved it

**Comment by papac** [comment]
Thank.
